dist: xenial
sudo: true

language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7
- 3.8
- pypy2.7-6.0
- pypy3.5

install:
- pip install tox-travis
script:
- tox

stages:
- lint
- test

jobs:
  include:
  - { stage: lint, python: 3.7, env: TOXENV=bandit }
  - { stage: lint, python: 3.7, env: TOXENV=flake8 }
  - { stage: lint, python: 3.7, env: TOXENV=pylint }
  - { stage: lint, python: 3.7, env: TOXENV=readme }
